//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SilverlightMediaFramework.Plugins.HLS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HLSMediaPluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HLSMediaPluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SilverlightMediaFramework.Plugins.HLS.Resources.HLSMediaPluginResources" +
                            "", typeof(HLSMediaPluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Element Generated Log - Reason: {0}.
        /// </summary>
        internal static string MediaElementGeneratedLogMessageFormat {
            get {
                return ResourceManager.GetString("MediaElementGeneratedLogMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLSMediaPlugin Instantiated.
        /// </summary>
        internal static string MediaPluginInstantiatedLogMessage {
            get {
                return ResourceManager.GetString("MediaPluginInstantiatedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLSMediaPlugin Loaded.
        /// </summary>
        internal static string MediaPluginLoadedLogMessage {
            get {
                return ResourceManager.GetString("MediaPluginLoadedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLSMediaPlugin Unloaded.
        /// </summary>
        internal static string MediaPluginUnloadedLogMessage {
            get {
                return ResourceManager.GetString("MediaPluginUnloadedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline Marker Reached - Time: {0} Type: {1} Text: {2}.
        /// </summary>
        internal static string TimelineMarkerReached {
            get {
                return ResourceManager.GetString("TimelineMarkerReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid Playback Rate.
        /// </summary>
        internal static string UnsupportedPlaybackRateMessage {
            get {
                return ResourceManager.GetString("UnsupportedPlaybackRateMessage", resourceCulture);
            }
        }
    }
}
